#ifndef STATUS_H_
#define STATUS_H_

typedef enum{
  STATUS_OK,
  STATUS_ERR_TIMEOUT,
  STATUS_ERR_STATE,
  STATUS_ERR_PARAM,
  STATUS_ERR_CHECKSUM,
  STATUS_ERR_BUSY
}status_t;

#endif /* STATUS_H_ */
